export enum EEnvType {
  PORT = 'PORT',
  TRANSPORT_PORT = 'TRANSPORT_PORT',
  JWT_SECRET_KEY = 'JWT_SECRET_KEY',
  JWT_EXPIRATION_TIME = 'JWT_EXPIRATION_TIME',
  FALLBACK_LANGUAGE = 'FALLBACK_LANGUAGE',
  NATS_ENABLED = 'NATS_ENABLED',

  NATS_HOST = 'NATS_HOST',
  NATS_PORT = 'NATS_PORT',
}
